# Default values for goflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sq/kopf
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

# use --set workdir=${PWD} to replace it
workdir: /home/manager/bgp-spkr/helm-dev

nodeSelector: {}

tolerations: []

affinity: {}

# deploy pod for dev
dev:
  enabled: true

### squid - end

